apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ce-aa-ng-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cepg-aa-std-rwmany
  resources:
    requests:
      storage: 1Gi
